api_port: 8001
library:
    music:
        libmime: audio
        libpath: []
    photos:
        libmime: image
        libpath: []
    tv:
        libmime: video
        libpath: []
    movies:
        libmime: video
        libpath: []
    other:
        libmime: ''
        libpath: []
